### ISSUE TITLE
Ticker issue

### ISSUE THREAD

**Issue by monkeydust** [tradytics/eiten#17]
Hi how does one load in this https://finance.yahoo.com/quote/ICNYB.PA?p=ICNYB.PA ?

Tried different combo's of ticker but throws error or ignored (if use ICNYB.PA) ... 

Txs

**Comment by silvavn** [comment]
Try using a parisian base index instead of the SPY, that worked for me locally.

**Comment by tradytics** [comment]
Thank you for the solution @silvavn. Closing this right now. If the problem persists, please create another issue or let me know and I'll reopen this.
