### ISSUE TITLE
The whole thing may not as good as it looks like

### ISSUE THREAD

**Issue by rongzhou** [tradytics/eiten#18]
There is a serious issue for the portfolio weights. When run for long only, there is not code do divide sum(weights). Total weights is almost round 2.5 to 4. So the result scaled 2.5 to 4. Because the project use the bull market data. So we got a pretty beautiful cumsum curve.

**Comment by silvavn** [comment]
@rongzhou you could simply apply a ratio calculation to find the percentages. 
Regarding data, you are free to used any data you want. The project comes with a data scraping tool, so its up to you if you want to use data from 2020 or from 2008.

**Comment by tradytics** [comment]
Thanks @silvavn - that's true @rongzhou, I forgot to add the normalization calculation for long only weights. Please feel free to add it and test it on any time period. This isn't a show off, the code and tools are there for everyone to test and actually see where they perform and where they don't.

Thank you for the comments. Going to close this now, please submit a PR if you solve this issue. I'll see if I can over the weekend.
